src/app/assets/nav.js
src/app/assets/search.js

Make the text color full

---

package-lock.json
package.json
src/app/customizer/LoremIpsumGenerator/page.js

#17 
1. moved the paragraph number and generate/copy buttons to the top of the text pane
2. changed the background of the text pane to white
3. The text pane has a maximum size to prevent it from overflowing the screen. The text pane expands to fill most of the screen to allow for easy reading for the user

Change color of text pane for Lorem Ipsum Generator - Pull Request

---

package-lock.json
package.json
src/app/customizer/LoremIpsumGenerator/page.js

Reverts Bashamega/WebDevTools#18

Revert "Change color of text pane for Lorem Ipsum Generator - Pull Request"

---

src/app/customizer/button/page.js

Solved open issue drop down menu

Added dropdown lists for font family, weight, cursor

---

package-lock.json
package.json
src/app/assets/nav.js
src/app/codeedit/page.js
src/app/customizer/CupcakeIpsumGenerator/page.js
src/app/customizer/LoremIpsumGenerator/page.js
src/app/customizer/button/page.js
src/app/customizer/conversionCalculator/page.js
src/app/globals.css
src/app/layout.js
src/app/page.js

Made navbar responsive 
fixes issue #25 
Note individual tool navbar is not done yet I can do it if you want do let me know

fix navbar

---

package-lock.json
package.json
src/app/assets/nav.js
src/app/assets/search.js
src/app/customizer/colorPicker/page.js
src/app/globals.css

(#29)
Added the color picker and its also responsive.
Would have liked to get the button and text to change to the selected color but it didnt work with react-colorful for some reason.
If you are happy with it you can merge but I can also rewrite it with a different color library to get that to work.

Added Color Picker

---

src/app/codeedit/page.js

Just Changed the file name to white.

Changed the Color of files in code editor

---

package-lock.json
package.json
src/app/customizer/colorPicker/page.js

I have added - 
- toast messages
- Improved buttons
- Made the page responsive
@Bashamega check it and merge it

Improved color picker page

---

src/app/assets/nav.js

Description:This PR adresses the issue #37 .
Changes made: WebDevTools/src/app/assets/nav.js
-Introduced a useRef to capture a reference to the dropdown element.
-Implemented an event listener on the document to detect clicks outside of the dropdown area.
-Created a handleClickOutside function that checks whether a click occurred outside of the dropdown and closes it accordingly.
-Updated the code within the Nav component to utilize the new event handling mechanism.
Do let me know if there is any discrepancy.
Thank You

Title:Dropdown Now Closing When Clicked Outside

---

src/app/MD/page.js
src/app/assets/nav.js

fixes #39 
@Bashamega Improved markdown better and made it responsive
Do review and merge it :)

improved markdown editor

---

src/app/customizer/button/page.js

fixes #40 
@Bashamega I have improved the button-customizer 
do have a look and merge it :)

improved button customizer

---

src/app/customizer/conversionCalculator/page.js

fixes #43 
Fixed layout and made the page responsive

Conversion calculator fix

---

src/app/page.js

Fixed Contributors Image aligned to the center.
Example screenshots
Before: 
After:

Fixed Contributors Image

---

src/app/MD/page.js
src/app/assets/nav.js
src/app/page.js
tailwind.config.js

Added hover to buttons and contributions cards.

add hover effect

---

src/app/page.js

Added icons to footer component, fixed #57.
Screenshot

added icons to footer

---

src/app/not-found.jsx

Fixes WebDevTools/404Page#82
Closes #82

Add 404 page

---

.github/workflows/greet.yml
src/app/snippet/page.jsx

Why?
Greet users with a welcome message upon their first PR
Related issues
fixes #85

Implement Github Actions Bot to Welcome new PRs

---

.github/workflows/greet.yml

Fixed greet.yml

---

.github/workflows/greet.yml

Fixes #92 and #89's merging issues.

Implement Github Action Bot to welcome PR's from user

---

package-lock.json
package.json
src/app/codeedit/page.jsx
src/app/components/Footer/index.jsx
src/app/components/hamburger-menu.jsx
src/app/components/nav.jsx
src/app/components/search.jsx
src/app/customizer/CupcakeIpsumGenerator/page.jsx
src/app/customizer/LoremIpsumGenerator/page.jsx
src/app/customizer/box-shadow-generator/page.jsx
src/app/customizer/button/page.jsx
src/app/customizer/colorPicker/page.jsx
src/app/customizer/conversionCalculator/page.jsx
src/app/customizer/gradient-generator/page.jsx
src/app/not-found.jsx
src/app/page.jsx
src/app/snippet/page.jsx

- Make website responsive
- Add mobile first approach

Feature/responsive design (#77)

---

src/app/contribute/page.jsx

added gap between contribute div and footer component

---

src/app/components/search.jsx

fix #130 
The link tag wasn't imported.

fixed search

---

src/app/customizer/button/page.jsx
src/app/customizer/conversionCalculator/page.jsx

The light theme was not working properly on some pages, so I fixed it.

Bug fix for conversion calculator and button component

---

src/app/contribute/page.jsx

The GitHub button color wasn't appearing properly on light mode.

fix github button color on light mode

---

src/app/codeedit/components/FooterOptions.jsx
src/app/codeedit/components/Sider.jsx
src/app/customizer/box-shadow-generator/page.jsx
src/app/customizer/button/page.jsx

#142 Light mode Fixed
Here changed text colors in light mode..
changed the text color in Button customizer, Box Shadow generator & Code Editor Sections

#142 Light mode fixed

---

src/app/contribute/page.jsx

Removed the bots from the contributors list

---

src/app/components/nav.jsx

Change Dropdown menu's Text color and added <hr />

---

src/app/customizer/JsonGenerator/components/CardForm.jsx
src/app/customizer/JsonGenerator/components/Item.jsx
src/app/customizer/JsonGenerator/page.js

Added gap between content and footer.

added gap in JsonGenerator 

---

src/app/components/nav.jsx
src/app/customizer/JsonGenerator/utils.js

Added a new field type for `email`
Fix #150

added email field type

---

src/app/customizer/JsonGenerator/components/CardForm.jsx
src/app/customizer/JsonGenerator/components/Item.jsx

Fixed issue #152
changed text to visible...

Fixed #152

---

package-lock.json
package.json
src/app/components/nav.jsx
src/app/customizer/Readme-generator/page.jsx
src/app/customizer/conversionCalculator/page.jsx
src/app/page.jsx
src/db/tools.json

Added Readme.md file generator

readme file generator added

---

src/app/customizer/Readme-generator/page.jsx

Removed useless **code** tag under the ``License``  row.

removed useless tag

---

src/app/customizer/button/page.jsx

Tailwind css

---

package-lock.json
package.json
src/app/asciiDoc/components/Editor.jsx
src/app/asciiDoc/page.jsx
src/app/customizer/button/page.jsx

Ascii doc editor

---

src/app/MD/page.jsx
src/app/components/icons/moonicon.js
src/app/components/icons/sunicon.js
src/app/components/nav.jsx
src/app/components/navbar.jsx

Add toggle icon for theme

---

package-lock.json
src/app/codeedit/page.jsx

fix title name /codeedit

---

package-lock.json
src/app/MD/page.jsx
src/app/customizer/box-shadow-generator/page.jsx
src/app/customizer/conversionCalculator/page.jsx

Black space

---

src/app/api/posts/route.js
src/app/api/users/[userId]/route.js
src/app/api/users/route.js
src/db/posts.json
src/db/users.json

endpoints for users and posts

---

src/app/api/posts/route.js
src/app/api/users/[userId]/route.js
src/app/api/users/route.js
src/app/endpoints/page.jsx
src/db/posts.json
src/db/tools.json
src/db/users.json

Added page that describes the endpoints for users and posts.  Also updated the /api/users and /api/posts endpoints to default to page 1 if no page parameter is provided

Endpoints page

---

package-lock.json
package.json
src/app/api/posts/route.js
src/app/api/users/[userId]/route.js
src/app/api/users/route.js
src/app/convert/html-jsx/components/editor.jsx
src/app/convert/html-jsx/page.jsx
src/app/endpoints/page.jsx
src/app/sitemap.xml
src/db/posts.json
src/db/tools.json

Html to jsx

---

src/app/components/nav.jsx
src/app/gh-finder/page.jsx

- Removed the extra space in the dropdown menu inside the navbar and added "overflow-hidden" to round the corners.
- Made styling changes in the GitHub issue finder, primarily for mobile view.

fix: minor styling change

---

package-lock.json
src/app/customizer/conversionCalculator/page.jsx

refactor Conversion Calculator

---

package-lock.json
package.json
src/app/components/hamburger-menu.jsx
src/app/components/nav.jsx
src/app/components/navbar.jsx
src/app/convert/components/editor.jsx
src/app/convert/json-yaml/page.jsx
src/app/sitemap.xml
src/db/tools.json

resolves (https://github.com/Bashamega/WebDevTools/issues/218)
Adds:
`/convert/json-yaml` route

Json to yaml

---

package-lock.json
src/app/api/posts/route.js
src/app/api/users/[userId]/route.js
src/app/api/users/route.js
src/app/components/search.jsx
src/app/contribute/page.jsx
src/app/convert/html-jsx/page.jsx
src/app/convert/img-svg/components/svg-converter.jsx
src/app/customizer/box-shadow-generator/page.jsx
src/app/gh-finder/page.jsx

Integrate caching to all our fetch calls so we don't get blocked by github

Fetch calls integrated 

---

src/app/MD/page.jsx

changed the flickering caused in /MD

---

src/db/codesnippets/posts/python/article2.md
src/db/codesnippets/posts/python/content.json

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #(issue)

Article: Get the date of creation of a file

---

src/app/cs/[language]/page.jsx

I have added a search functionality for the code snippets

feat: Added Search

---

README.md
src/db/codesnippets/posts/java/checkifvariableisanarray.md
src/db/codesnippets/posts/java/content.json
src/db/codesnippets/posts/java/getcurrenttime.md
src/db/codesnippets/posts/java/logtexttoconsole.md

feat: Add code snippets in Java and fix README

---

package-lock.json
src/app/resume-builder/Preview.jsx
src/app/resume-builder/ResumePDF.jsx

This PR adds relevant icons next to the contact details (Phone number, Email, LinkedIn, GitHub, and Website) in the resume builder section to enhance visual clarity and improve user experience.
Fixes #266

Add Icons to contacts in Resume

---

src/db/codesnippets/categories.json
src/db/codesnippets/posts/python/article3.md
src/db/codesnippets/posts/python/content.json
src/db/codesnippets/posts/react/article1.md
src/db/codesnippets/posts/react/article2.md
src/db/codesnippets/posts/react/article3.md
src/db/codesnippets/posts/react/content.json

I have added 4 code snippets( 1 in python and 3 in react)
Fixes #261

article: React and python snippets 

---

src/app/components/dropdowns/dropdown.jsx
src/app/components/nav.jsx
src/app/globals.css
src/app/layout.js

Added custom scrollbar and fixed dropdown menu overflow. 
Fixes #(issue)
none

Added custom scrollbar and fix overflow in dropdown menu

---

src/app/components/dropdowns/dropdown.jsx

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #274

patch: responsive dropdown menu

---

src/db/codesnippets/posts/javascript/content.json
src/db/codesnippets/posts/javascript/limitfunctionexecutionrate.md

- Added a new Markdown file with a throttle function example. 
- Updated JSON file to include the new snippet.
Fixes #(issue)

feat: add throttle function snippet to JavaScript category

---

src/db/codesnippets/posts/javascript/content.json
src/db/codesnippets/posts/javascript/optimizepageloadtimewithlazyloadingimages.md

- Implemented lazy loading using IntersectionObserver API
- Updated images to use `data-src` attribute for deferred loading
- Added lazy loading initialization on DOMContentLoaded
Fixes #(issue)

feat(lazy-load): add lazy loading for images

---

src/app/globals.css

Just changed the global css file to introduce the variable used for rounded-lg
Fixes #320

rounded corner added in all components

---

src/db/api.json

Added 5 more APIs

---

src/app/gh-finder/modal.jsx
src/app/gh-finder/page.jsx

Fixed github issue finder

---

src/db/api.json

This pull request adds new APIs to the `api.json` file as part of the issue #324.
I have included the following APIs: OpenAI API, Zoom API, NewsAPI, Marvel API, Twilio API.
#324

Added new APIs to the api.json file

---

src/db/api.json

Added 5 more APIs to the api.json file.

Add 5 more APIs

---

src/components/hamburger-menu.jsx
src/components/nav.jsx
tailwind.config.js

bug fixed, now theme toggle works in hamburger

---

.github/workflows/jest_tests.yml
.gitignore
.husky/pre-commit
__tests__/test.test.jsx
jest.config.js
jest.setup.js
package-lock.json
package.json

* fixing FEATURE issue #369
* implementing Jest - testing library in project for test coverage
* better error detection
* test runner, assertions, code coverage, mocking

feature #369: implemented tests setup by Jest library

---

src/app/contribute/page.jsx

Enhanced the UX by making the contributors section more friendly and accessible on hover.
Fixes #371
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ X] My code follows the style guidelines of this project
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass locally with my changes
- [ X] Any dependent changes have been merged and published in downstream modules
Before:
After:

Enhanced the UI of contributors section for better UX

---

src/app/customizer/colorPicker/colorPicker.test.js

Added tests for Color Picker component.
Fixes #389

add color picker tests

---

.github/PULL_REQUEST_TEMPLATE.md
contributing.md
src/db/tools.json

Updated tool names and added documentation for future tool naming.
Fixes #411

Updated tool naming and added documentation for naming convention

---

package-lock.json
src/app/customizer/conversionCalculator/page.jsx
src/app/customizer/conversionCalculator/tests/ConversionCalculator.test.js

Adds Jest tests for Conversion Calculator
Fixes #387

test: add tests for Conversion Calculator

---

src/app/customizer/JsonGenerator/components/CopyButton.jsx
src/app/customizer/JsonGenerator/components/PreviewSection.jsx

This feature adds Copy Functionality to JSON Generator
Fixes #420

Implemented Copy Functionality for JSON generator

---

src/app/customizer/Readme-generator/page.jsx
src/app/layout.js
src/components/nav.jsx
src/components/navbar.jsx

fixed Nav and Navbar
